/**
 * @version		$Id: fpss.packed.js 619 2011-08-08 20:03:34Z joomlaworks $
 * @package		Frontpage Slideshow (standalone)
 * @author		JoomlaWorks http://www.joomlaworks.gr
 * @copyright	Copyright (c) 2006-2011 JoomlaWorks Ltd. All rights reserved.
 * @license		Commercial - This code cannot be redistributed without permission from JoomlaWorks Ltd.
 */

eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('(3($){$.1e.1f=3(t){2 u={\'S\':1g,\'w\':T,\'U\':T,\'V\':\'C\',\'W\':x,\'H\':\'1h\',\'I\':\'1i\'};y X.1j(3(){4(t){$.1k(u,t)}2 f="D-1l";2 g="D-1m";2 h="D";2 i="1n";2 j="-1o";2 k="E-Y";2 l=\'E-1p\';2 m=\'E-1q\';2 n=\'E-Y\';4(!$(\'#\'+f))y v;2 o=v;2 p,5,9;2 q=$(\'#\'+k);$(\'#\'+g).Z();$(\'#D-1r\').Z();3 1s(){};3 1t(){};3 1u(){};3 1v(){};2 r=$(\'.10\').11(\'.\'+h);2 s=$(\'.10\').11(\'.\'+i);4(r.F==0||s.F==0)y v;r.J(\'12\',\'13\');$(r[0]).J(\'12\',\'1w\');$(s[0]).1x(i+j);$(\'#\'+g).1y(u.U).14(u.w,3(){4(u.W&&o==v){K()}z{L()}$(\'#\'+f).J(\'1z\',\'13\');15()});s.1A(u.V,3(a){a.G();4($(\':1B\').F)y v;B(u.w,16.1C(X,s))});$(\'#\'+l).C(3(a){a.G();B(u.w,\'17\')});$(\'#\'+m).C(3(a){a.G();B(u.w,\'M\')});$(\'#\'+n).C(3(a){a.G();4(o){K()}z{L()}});3 B(a,b){2 c=r.F;4(c<=1)y v;4(1D 5==\'1E\')5=0;4(b==\'M\'){4(5==c-1){9=0}z{9=5+1}}z 4(b==\'17\'){4(5==0){9=c-1}z{9=5-1}}z{9=b}4(5==9)y v;$(r[5]).18(x,x).1F(a);s[5].A=i;$(r[9]).18(x,x).14(a);s[9].A=i+j;5=9}3 19(){o=v;p=1G(3(){B(u.w,\'M\')},u.S)}3 1a(){o=x;1H(p)}3 L(){q.1b(u.H);q.1c(\'1d\',u.H);1a()}3 K(){q.1b(u.I);q.1c(\'1d\',u.I);19()}3 15(){2 a=1I.1J("1K")[0];2 b=a.A;2 c=N.O.P().Q(\'R 6\')!=-1;2 d=N.O.P().Q(\'R 7\')!=-1;2 e=N.O.P().Q(\'R 8\')!=-1;4(c)a.A=b+\' 1L\';4(d)a.A=b+\' 1M\';4(e)a.A=b+\' 1N\'}})}})(16);',62,112,'||var|function|if|currentIndex||||targetIndex||||||||||||||||||||||false|crossFadeSpeed|true|return|else|className|xFade|click|slide|fpss|length|preventDefault|textPlay|textPause|css|buttonPause|buttonPlay|next|navigator|userAgent|toLowerCase|indexOf|msie|crossFadeDelay|1000|loaderDelay|navEvent|autoslide|this|container_playButton|hide|fpssModuleContainer|find|display|none|fadeIn|ieBrowserDetect|jQuery|previous|stop|startSlideshow|stopSlideshow|html|attr|title|fn|frontpageSlideshow|6000|Play|Pause|each|extend|wrapper|outer|navi|active|container_prev|container_next|loading|showPrev|showNext|clearSlide|ppButtonClicked|block|addClass|delay|background|bind|animated|inArray|typeof|undefined|fadeOut|setInterval|clearInterval|document|getElementsByTagName|body|fpssIsIE6|fpssIsIE7|fpssIsIE8'.split('|'),0,{}))
